// লগইন/সাইনআপ/পাসওয়ার্ড/onboarding পেজের লেখা — English (ডিফল্ট) ও বাংলা। ভাষা মার্কেটিং সাইটের
// একই কুকি (gz_lang) থেকে আসে, তাই সাইটের ভাষা আর লগইন পেজের ভাষা সবসময় এক। কাঠামো `en` থেকে
// টাইপ হয়, তাই কোনো key বাদ পড়লে build এ ধরা পড়ে। ড্যাশবোর্ড এখনো শুধু বাংলা।
export const en = {
  or: "or continue with",
  social: { google: "Google", facebook: "Facebook", linkedin: "LinkedIn" },
  socialError: "Couldn't start sign-in with {provider}. It may not be set up yet — please use email instead.",
  showPassword: "Show password",
  hidePassword: "Hide password",
  termsPrefix: "By continuing you agree to our",
  terms: "Terms",
  and: "and",
  privacy: "Privacy Policy",
  termsSuffix: ".",

  login: {
    title: "Log in",
    email: "Email",
    password: "Password",
    forgot: "Forgot password?",
    submit: "Log in",
    submitting: "Logging in...",
    noAccount: "Don't have an account?",
    signupLink: "Sign up",
    invalid: "Incorrect email or password",
    oauthFailed: "Sign-in didn't complete. Please try again, or use your email.",
  },
  signup: {
    title: "Create your account",
    name: "Your name",
    email: "Email",
    password: "Password",
    hint: "At least 6 characters",
    submit: "Sign up",
    submitting: "Creating...",
    haveAccount: "Already have an account?",
    loginLink: "Log in",
    doneTitle: "Check your email",
    doneBody: "We sent a confirmation link to your email. Click it to confirm your account, then log in.",
    doneLink: "Go to log in",
  },
  forgot: {
    title: "Forgot your password?",
    subtitle: "Enter your email and we'll send you a reset link.",
    email: "Email",
    submit: "Send reset link",
    submitting: "Sending...",
    remembered: "Remembered it?",
    loginLink: "Log in",
    doneTitle: "Check your email",
    doneBody: "If that email is in our system, we've sent a password reset link. Click it to set a new password.",
    doneLink: "Back to log in",
  },
  reset: {
    title: "Set a new password",
    newPassword: "New password",
    hint: "At least 6 characters",
    confirm: "Re-enter password",
    submit: "Save password",
    submitting: "Saving...",
    tooShort: "Password must be at least 6 characters",
    mismatch: "The two passwords don't match",
    doneTitle: "Password changed",
    doneLink: "Log in",
    invalidTitle: "This link has expired",
    invalidBody: "This reset link no longer works — please request a new one.",
    invalidLink: "Try again",
    verifying: "Verifying link...",
  },
  onboarding: {
    title: "Create your workspace",
    body: "For example, your business name — your numbers and campaigns will be managed under it.",
    label: "Workspace name",
    placeholder: "e.g. My Shop",
    submit: "Create",
    submitting: "Creating...",
  },
};

export type AuthContent = typeof en;

export const bn: AuthContent = {
  or: "অথবা এর মাধ্যমে চালিয়ে যান",
  social: { google: "Google", facebook: "Facebook", linkedin: "LinkedIn" },
  socialError: "{provider} দিয়ে সাইন-ইন শুরু করা যায়নি। হয়তো এখনো সেটআপ হয়নি — ইমেইল দিয়ে চেষ্টা করুন।",
  showPassword: "পাসওয়ার্ড দেখান",
  hidePassword: "পাসওয়ার্ড লুকান",
  termsPrefix: "চালিয়ে গেলে আপনি আমাদের",
  terms: "শর্তাবলী",
  and: "ও",
  privacy: "গোপনীয়তা নীতি",
  termsSuffix: " মেনে নিচ্ছেন।",

  login: {
    title: "লগইন করুন",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    forgot: "পাসওয়ার্ড ভুলে গেছেন?",
    submit: "লগইন",
    submitting: "লগইন হচ্ছে...",
    noAccount: "অ্যাকাউন্ট নেই?",
    signupLink: "সাইনআপ করুন",
    invalid: "ইমেইল বা পাসওয়ার্ড ভুল হয়েছে",
    oauthFailed: "সাইন-ইন সম্পন্ন হয়নি। আবার চেষ্টা করুন, অথবা ইমেইল ব্যবহার করুন।",
  },
  signup: {
    title: "নতুন অ্যাকাউন্ট বানান",
    name: "আপনার নাম",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    hint: "কমপক্ষে ৬ ক্যারেক্টার",
    submit: "সাইনআপ",
    submitting: "তৈরি হচ্ছে...",
    haveAccount: "অ্যাকাউন্ট আছে?",
    loginLink: "লগইন করুন",
    doneTitle: "ইমেইল চেক করুন",
    doneBody: "আপনার ইমেইলে একটা কনফার্মেশন লিংক পাঠানো হয়েছে। লিংকে ক্লিক করে অ্যাকাউন্ট কনফার্ম করুন, তারপর লগইন করুন।",
    doneLink: "লগইন পেজে যান",
  },
  forgot: {
    title: "পাসওয়ার্ড ভুলে গেছেন?",
    subtitle: "আপনার ইমেইল দিন, একটা রিসেট লিংক পাঠিয়ে দিচ্ছি।",
    email: "ইমেইল",
    submit: "রিসেট লিংক পাঠান",
    submitting: "পাঠানো হচ্ছে...",
    remembered: "মনে পড়েছে?",
    loginLink: "লগইন করুন",
    doneTitle: "ইমেইল চেক করুন",
    doneBody: "ইমেইলটা আমাদের সিস্টেমে থাকলে একটা পাসওয়ার্ড রিসেট লিংক পাঠানো হয়েছে। লিংকে ক্লিক করে নতুন পাসওয়ার্ড বসান।",
    doneLink: "লগইন পেজে ফিরুন",
  },
  reset: {
    title: "নতুন পাসওয়ার্ড দিন",
    newPassword: "নতুন পাসওয়ার্ড",
    hint: "কমপক্ষে ৬ ক্যারেক্টার",
    confirm: "আবার লিখুন",
    submit: "পাসওয়ার্ড সেভ করুন",
    submitting: "সেভ হচ্ছে...",
    tooShort: "পাসওয়ার্ড কমপক্ষে ৬ ক্যারেক্টার হতে হবে",
    mismatch: "দুই পাসওয়ার্ড মিলছে না",
    doneTitle: "পাসওয়ার্ড বদলানো হয়েছে",
    doneLink: "লগইন করুন",
    invalidTitle: "লিংকের মেয়াদ শেষ হয়ে গেছে",
    invalidBody: "এই রিসেট লিংকটা আর কাজ করছে না — আবার একটা নতুন লিংক চেয়ে নিন।",
    invalidLink: "আবার চেষ্টা করুন",
    verifying: "লিংক যাচাই হচ্ছে...",
  },
  onboarding: {
    title: "আপনার Workspace বানান",
    body: "যেমন আপনার ব্যবসার নাম — এটা দিয়ে পরে আপনার নাম্বার, ক্যাম্পেইন সব ম্যানেজ হবে।",
    label: "Workspace এর নাম",
    placeholder: "যেমন: আমার শপ",
    submit: "তৈরি করুন",
    submitting: "তৈরি হচ্ছে...",
  },
};
